#!/bin/sh

#Usage: ./to_ghpages

PUBLIC_URL="https://paulgreg.me/flashcard" npm run build

BRANCH=$(git symbolic-ref -q HEAD)
BRANCH=${BRANCH##refs/heads/}
echo "Actual branch: $BRANCH"

echo "Saving modified files..."
git commit -am "Save uncommited changes (WIP)"

echo "Building GitHub Page branch..."
git branch --delete --force gh-pages
git checkout --orphan gh-pages
cp src/settings.json.dist src/settings.json
git add -f build
git commit -m "Rebuild GitHub pages"

echo "Pushing GitHub Page branch..."
git filter-branch -f --prune-empty --subdirectory-filter build && git push -f origin gh-pages && git checkout -f $BRANCH
